# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'CrossWorld' do

  pod 'TPKeyboardAvoiding'
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'EVReflection'
  pod 'NVActivityIndicatorView'
  pod 'DropDown'
  pod 'SwiftMessages'
  pod 'PopupController'
  pod 'IBAnimatable'
  pod 'Bond'
  pod 'HCSStarRatingView'
  pod 'ImageSlideshow'
  pod 'ImageSlideshow/Kingfisher'
  pod 'AttributedTextView'
  pod 'SwiftDate'
  pod 'ImagePicker'
  pod 'CountryPickerSwift'
  pod 'XCDYouTubeKit'
  
  #Facebook SDK
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKMessengerShareKit'

end
